apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: default
data:
  LOG_LEVEL: "INFO"
  SPRING_PROFILES_ACTIVE: "prod"
  datasource-url: "jdbc:postgresql://postgres:5432/ecommerce"
  kafka-bootstrap-servers: "kafka:9092"
  spring-jpa-hibernate-ddl-auto: "update"
  spring-jpa-show-sql: "false"
  logging-level-root: "INFO"
  logging-level-com-ecommerce: "INFO"
