apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: default
data:
  LOG_LEVEL: "INFO"
  datasource-url: "jdbc:postgresql://postgres:5432/ecommerce"
  kafka-bootstrap-servers: "kafka:9092"

